spring:
  application:
    name: Movie Review System. Back End.
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: admin
    password: admin
    platform: h2
    h2:
      console:
        enabled: true
        path: /h2
  jpa:
    show-sql: true
    hibernate:
      formatSql: true
      ddl-auto: update
    databasePlatform: "org.hibernate.dialect.H2Dialect"
server:
  port: 9000